function main(args) {
console.log("read file: " + args[0]);
  var data = FS.readFile(args[0]);
  var new_data = null;

  var blob_new = new Blob([data.buffer, data.buffer]);

  var f_reader = new FileReader();

  f_reader.onload = function(){
    new_data = this.result;
console.log("write file: " + args[1]);
    FS.writeFile(args[1], new_data);
    exit();
  }
  f_reader.readAsArrayBuffer(blob_new);
}

//TO EXECUTE JAVASCRIPT THAT WAS NOT GENERATED BY EMSCRIPTEN FOLLOW THESE STEPS:
//
//1. Build your javascript app in a seperate file
//2. Create a function named "main" which is the entry point of execution
//3. Call the "exit" function to quit your javascript app(all events done) 
//4. Append this file to your javascript app file

//arguments are passed to main function
//input and output files are accessed via FS.readFile and FS.writeFile


Module['Main']      = main;
Module['arguments'] = arguments;

function getUniqueRunDependency(id){
  return id;
}

function check_dependencies(){  
  if(dependencies == 0){
    clearInterval(prerun_interval);
    Module['Main'](Module['arguments']);
  }
}

function exit(){
  Module['postRun'](); 
}

var FS = {
  files     : {},
  writeFile : function (path, data, encoding){ this.files[path] = data; },
  readFile  : function (path, options){ return this.files[path]; }
};

var dependencies = 0;
Module['addRunDependency']    = function (id){dependencies++};
Module['removeRunDependency'] = function (id){dependencies--};
Module['preRun']();

var prerun_interval = setInterval(check_dependencies, 0);
